package com.imagine.martinhost;

import android.app.Activity;
import android.content.Intent;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.view.Gravity;
import android.widget.*;

public final class GamesActivity extends Activity {
 @Override public void onCreate(Bundle b){super.onCreate(b);build();}
 private void build(){
  getWindow().setStatusBarColor(0xFF060711);getWindow().setNavigationBarColor(0xFF060711);
  LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(0xFF060711);root.setPadding(dp(14),dp(9),dp(14),dp(8));
  LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);TextView back=t("‹",32,Color.WHITE,true);back.setGravity(Gravity.CENTER);back.setOnClickListener(v->finish());head.addView(back,new LinearLayout.LayoutParams(dp(44),dp(44)));TextView title=t("Игры и конкурсы",22,Color.WHITE,true);title.setGravity(Gravity.CENTER);head.addView(title,new LinearLayout.LayoutParams(0,dp(44),1));TextView crown=t("♛",23,0xFFFFC54A,true);crown.setGravity(Gravity.CENTER);head.addView(crown,new LinearLayout.LayoutParams(dp(44),dp(44)));root.addView(head);
  HorizontalScrollView hs=new HorizontalScrollView(this);hs.setHorizontalScrollBarEnabled(false);LinearLayout chips=new LinearLayout(this);String[] cats={"Все","Музыка","Интеллект","Фото","Активные"};for(int i=0;i<cats.length;i++){TextView c=t(cats[i],12,Color.WHITE,i==0);c.setGravity(Gravity.CENTER);c.setBackground(i==0?gradStroke(new int[]{0xFF2247FF,0xFF7E2BEE},16,0x557D89FF):glass(16));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(dp(92),dp(36));p.setMargins(0,0,dp(8),0);chips.addView(c,p);}hs.addView(chips);root.addView(hs,new LinearLayout.LayoutParams(-1,dp(46)));
  FrameLayout hero=new FrameLayout(this);hero.setBackground(gradStroke(new int[]{0xFF0F1326,0xFF23104A,0xFF07111F},24,0x333D58A8));MartinSpriteView martin=new MartinSpriteView(this);martin.setState(MartinSpriteView.State.GAME);hero.addView(martin,new FrameLayout.LayoutParams(-1,-1));TextView label=t("Мартин объяснит правила и покажет пример перед каждым конкурсом",12,Color.WHITE,true);label.setGravity(Gravity.CENTER);label.setPadding(dp(10),dp(7),dp(10),dp(7));label.setBackground(gradStroke(new int[]{0xDD123AD7,0xDD7022E8},18,0x55FFFFFF));FrameLayout.LayoutParams lp=new FrameLayout.LayoutParams(-1,-2);lp.gravity=Gravity.BOTTOM;lp.setMargins(dp(16),0,dp(16),dp(12));hero.addView(label,lp);root.addView(hero,new LinearLayout.LayoutParams(-1,dp(180)));
  ScrollView sv=new ScrollView(this);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);String[][] games={{"🎵","Угадай мелодию","Хиты 90-х, 00-х и 2026","10–15 мин","#5826D8"},{"👥","Две звезды в одном лице","Угадай знаменитостей","10–15 мин","#C6641A"},{"🧠","Что? Где? Когда?","Логика, факты и вопросы с подвохом","15–20 мин","#0F7F72"},{"😈","Испорченные стишки","Проверка испорченности гостей","10 мин","#8D2BC1"},{"💬","Кто сказал эту цитату?","Известные люди и неожиданные ответы","10–15 мин","#B87C13"},{"🎶","Музыкальная машина времени","Угадай год и исполнителя","10–15 мин","#4934DE"}};for(String[] g:games)list.addView(card(g));sv.addView(list);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));root.addView(nav(1),new LinearLayout.LayoutParams(-1,dp(58)));setContentView(root);
 }
 private LinearLayout card(String[] g){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(10),dp(9),dp(10),dp(9));row.setBackground(glass(18));LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,dp(82));rp.setMargins(0,dp(8),0,0);row.setLayoutParams(rp);TextView ic=t(g[0],28,Color.WHITE,true);ic.setGravity(Gravity.CENTER);ic.setBackground(gradStroke(new int[]{Color.parseColor(g[4]),0xFF15152A},16,0x44FFFFFF));row.addView(ic,new LinearLayout.LayoutParams(dp(58),dp(58)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);tx.addView(t(g[1],15,Color.WHITE,true));tx.addView(t(g[2],11,0xFFACB0C1,false));tx.addView(t(g[3],10,0xFF797E94,false));LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(0,-2,1);tp.setMargins(dp(11),0,dp(6),0);row.addView(tx,tp);TextView go=t("Старт  ›",11,Color.WHITE,true);go.setGravity(Gravity.CENTER);go.setBackground(gradStroke(new int[]{0xFF223AE8,0xFF7A28F5},18,0x667A82FF));row.addView(go,new LinearLayout.LayoutParams(dp(72),dp(40)));return row;}
 private LinearLayout nav(int s){LinearLayout n=new LinearLayout(this);n.setPadding(dp(3),dp(3),dp(3),dp(3));n.setBackground(glass(18));String[] tt={"⌂\nМартин","🎮\nИгры","♫\nМузыка","🏆\nРейтинг","⚙\nНастройки"};Class<?>[] c={VisualHomeActivity.class,GamesActivity.class,MusicActivity.class,RankingActivity.class,VisualSettingsActivity.class};for(int i=0;i<tt.length;i++){final int x=i;TextView v=t(tt[i],10,i==s?0xFFB65CFF:0xFF8A8EA2,i==s);v.setGravity(Gravity.CENTER);if(i==s)v.setBackground(round(0x252E1A57,15));v.setOnClickListener(z->{if(x!=s){startActivity(new Intent(this,c[x]));overridePendingTransition(android.R.anim.fade_in,android.R.anim.fade_out);}});n.addView(v,new LinearLayout.LayoutParams(0,-1,1));}return n;}
 private TextView t(String s,int sp,int c,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(c);if(b)v.setTypeface(Typeface.DEFAULT_BOLD);v.setPadding(dp(5),dp(3),dp(5),dp(3));return v;}
 private GradientDrawable round(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
 private GradientDrawable glass(int r){return gradStroke(new int[]{0xE7161928,0xE70B0D17},r,0x3344517D);}
 private GradientDrawable gradStroke(int[] cs,int r,int stroke){GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TL_BR,cs);g.setCornerRadius(dp(r));g.setStroke(dp(1),stroke);return g;}
 private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
