package com.imagine.martinhost;

import android.Manifest;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.view.Gravity;
import android.widget.*;
import androidx.fragment.app.FragmentActivity;
import java.util.ArrayList;
import java.util.Locale;

/** Deadline-safe party launcher: voice-first, no 3D avatar. */
public final class LeanPartyActivity extends FragmentActivity {
 private static final int REQ=71; private MartinNeuralSpeaker neural; private GrokClient grok; private GroqTranscriber stt; private TurnManager turns; private ContinuousSpeechEngine audio; private MartinFaceTracker camera; private PartyDirector director; private VoiceOrbView orb; private TextView state,sub,heard,reply,aiDot,voiceDot,camDot; private Button mic; private boolean active,neuralReady; private String queued; private String qEmotion="neutral"; private float qEnergy=.55f;
 @Override public void onCreate(Bundle b){super.onCreate(b);buildUi();PartyAudioRouter.prepare(this);grok=new GrokClient(this);stt=new GroqTranscriber(this);director=new PartyDirector(this);turns=new TurnManager(s->runOnUiThread(()->turnState(s)));turns.setReleaseTailMs(650L);
  audio=new ContinuousSpeechEngine(this,turns,new ContinuousSpeechEngine.Listener(){public void onSpeechChunk(byte[] wav){turns.onUserFinal();stt.transcribe(wav,new GroqTranscriber.Callback(){public void onText(String t){runOnUiThread(()->handle(t));}public void onError(String e){runOnUiThread(()->{state.setText("Не расслышал");sub.setText("Повтори чуть ближе к телефону");turns.forceListen();});}});}public void onLevel(float rms,float noise,boolean speech){runOnUiThread(()->{if(turns.acceptMicForStt())orb.setLevel(Math.max(.02f,Math.min(1f,(rms+50f)/34f)));});}public void onStatus(String s){}public void onError(String e){runOnUiThread(()->sub.setText("Проверь микрофон"));}});
  neural=new MartinNeuralSpeaker(this,new MartinNeuralSpeaker.Listener(){public void onPreparing(String m){runOnUiThread(()->{voiceDot.setText("● ГОЛОС");voiceDot.setTextColor(0xFFFFB45E);sub.setText("Готовлю живой голос…");});}public void onReady(){runOnUiThread(()->{neuralReady=true;voiceDot.setTextColor(0xFF59E6A8);if(queued!=null){String q=queued,e=qEmotion;float en=qEnergy;queued=null;speakNow(q,e,en);}});}public void onStart(){runOnUiThread(()->{orb.setMode(VoiceOrbView.Mode.SPEAKING);state.setText("Говорю…");});}public void onLevel(float l){runOnUiThread(()->orb.setLevel(l));}public void onDone(){runOnUiThread(()->{orb.setLevel(.03f);orb.setMode(VoiceOrbView.Mode.LISTENING);turns.onAiSpeechDone();state.setText("Слушаю…");});}public void onError(String m){runOnUiThread(()->{neuralReady=false;voiceDot.setTextColor(0xFFFF6B6B);sub.setText(m);turns.onAiSpeechDone();});}});
  camera=new MartinFaceTracker(this,new MartinFaceTracker.Listener(){public void onLook(float x,float y,boolean visible){}public void onStatus(boolean ok,String m){runOnUiThread(()->{camDot.setText(ok?"● КАМЕРА":"○ КАМЕРА");camDot.setTextColor(ok?0xFF59E6A8:0xFF8E8999);sub.setText(ok?"Камера следит за присутствием гостей локально":"Камера выключена");});}});
  neural.prepare();requestPerms();refresh();startCamera(); }
 private void handle(String t){if(t==null||t.isBlank()){turns.forceListen();return;}heard.setText("Вы: "+t);String low=t.toLowerCase(Locale.ROOT);if(low.equals("стоп")||low.contains("мартин стоп")){stop();return;}if(director.mode()!=PartyDirector.Mode.FREE){run(director.onUserText(t));return;}int x=low.indexOf("мартин");if(x<0){turns.forceListen();return;}String q=t.substring(Math.min(t.length(),x+6)).replaceFirst("^[,.:;!?\\s—-]+","");if(q.isBlank())q="Поздоровайся с гостями коротко и естественно.";run(director.onUserText(q));}
 private void run(PartyDirector.Action a){if(a==null){turns.forceListen();return;}if(a.askAi){turns.onUserFinal();orb.setMode(VoiceOrbView.Mode.THINKING);state.setText("Думаю…");grok.reply(a.speech,new GrokClient.Callback(){public void onResult(String r){runOnUiThread(()->speak(clean(r),a.emotion,energy(a.emotion)));}public void onError(String e){runOnUiThread(()->{state.setText("Нет связи с AI");sub.setText("Проверь ключ и интернет");turns.forceListen();});}});}else speak(a.speech,a.emotion,energy(a.emotion));}
 private String clean(String s){if(s==null)return "";return s.replaceAll("\\[\\[[^\\]]*\\]\\]","").replaceAll("[*#_`~>]","").replaceAll("\\s+"," ").trim();}
 private float energy(String e){if(e==null)return .55f;e=e.toLowerCase(Locale.ROOT);if(e.contains("happy")||e.contains("playful")||e.contains("excited"))return .82f;if(e.contains("warm"))return .58f;return .62f;}
 private void speak(String s,String e,float en){s=clean(s);if(s.isBlank()){turns.forceListen();return;}reply.setText(s);turns.onAiWillSpeak();if(!neuralReady||!neural.isReady()){queued=s;qEmotion=e;qEnergy=en;state.setText("Готовлю голос…");neural.prepare();return;}speakNow(s,e,en);}
 private void speakNow(String s,String e,float en){orb.setMode(VoiceOrbView.Mode.SPEAKING);neural.speak(s,e,en);}
 private void turnState(TurnManager.State s){if(!active)return;switch(s){case LISTENING:orb.setMode(VoiceOrbView.Mode.LISTENING);state.setText("Слушаю…");break;case THINKING:orb.setMode(VoiceOrbView.Mode.THINKING);state.setText("Думаю…");break;case SPEAKING:orb.setMode(VoiceOrbView.Mode.SPEAKING);state.setText("Говорю…");break;case COOLDOWN:state.setText("Секунду…");break;}}
 private void start(){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPerms();return;}active=true;turns.forceListen();audio.start();orb.setMode(VoiceOrbView.Mode.LISTENING);state.setText("Слушаю…");mic.setText("■  ОСТАНОВИТЬ");}
 private void stop(){active=false;audio.stop();if(neural!=null)neural.stop();turns.forceListen();orb.setMode(VoiceOrbView.Mode.IDLE);orb.setLevel(.02f);state.setText("Готов к вечеринке");mic.setText("🎙  НАЧАТЬ");}
 private void startCamera(){if(checkSelfPermission(Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED)camera.start();}
 private void requestPerms(){ArrayList<String> p=new ArrayList<>();if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED)p.add(Manifest.permission.RECORD_AUDIO);if(checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED)p.add(Manifest.permission.CAMERA);if(android.os.Build.VERSION.SDK_INT>=31&&checkSelfPermission(Manifest.permission.BLUETOOTH_CONNECT)!=PackageManager.PERMISSION_GRANTED)p.add(Manifest.permission.BLUETOOTH_CONNECT);if(!p.isEmpty())requestPermissions(p.toArray(new String[0]),REQ);}
 @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==REQ){startCamera();if(active)start();}}
 private void refresh(){String ai=getSharedPreferences("martin",0).getString("ai_key","");aiDot.setTextColor(ai.isBlank()?0xFFFFB45E:0xFF59E6A8);}
 private void buildUi(){getWindow().setStatusBarColor(0xFF05060B);getWindow().setNavigationBarColor(0xFF05060B);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(10),dp(16),dp(12));root.setBackgroundColor(0xFF05060B);TextView title=tv("MARTIN • AI HOST",24,Color.WHITE,true);title.setGravity(Gravity.CENTER);root.addView(title,new LinearLayout.LayoutParams(-1,dp(48)));LinearLayout dots=new LinearLayout(this);dots.setGravity(Gravity.CENTER);aiDot=pill("● AI");voiceDot=pill("● ГОЛОС");camDot=pill("○ КАМЕРА");dots.addView(aiDot);dots.addView(voiceDot);dots.addView(camDot);root.addView(dots,new LinearLayout.LayoutParams(-1,dp(38)));orb=new VoiceOrbView(this);root.addView(orb,new LinearLayout.LayoutParams(-1,0,1));state=tv("Готов к вечеринке",21,Color.WHITE,true);state.setGravity(Gravity.CENTER);root.addView(state);sub=tv("Скажи: «Мартин, привет»",12,0xFF918B9E,false);sub.setGravity(Gravity.CENTER);root.addView(sub);heard=tv("",11,0xFF777184,false);heard.setGravity(Gravity.CENTER);root.addView(heard);reply=tv("",12,0xFFD0C0F8,false);reply.setGravity(Gravity.CENTER);reply.setMaxLines(3);root.addView(reply);mic=new Button(this);mic.setText("🎙  НАЧАТЬ");mic.setTextColor(Color.WHITE);mic.setTextSize(16);mic.setAllCaps(false);mic.setBackground(round(0xFF6A32F5,24));LinearLayout.LayoutParams mp=new LinearLayout.LayoutParams(-1,dp(58));mp.setMargins(0,dp(8),0,dp(8));root.addView(mic,mp);LinearLayout nav=new LinearLayout(this);nav.setGravity(Gravity.CENTER);Button game=btn("🎮 КОНКУРС");Button music=btn("♫ МУЗЫКА");Button set=btn("⚙ НАСТРОЙКИ");nav.addView(game,new LinearLayout.LayoutParams(0,dp(54),1));nav.addView(music,new LinearLayout.LayoutParams(0,dp(54),1));nav.addView(set,new LinearLayout.LayoutParams(0,dp(54),1));root.addView(nav);setContentView(root);mic.setOnClickListener(v->{if(active)stop();else start();});game.setOnClickListener(v->run(director.startChgk()));music.setOnClickListener(v->startActivity(new Intent(this,MusicActivity.class)));set.setOnClickListener(v->startActivity(new Intent(this,SettingsActivity.class)));}
 private TextView pill(String s){TextView v=tv(s,10,0xFF8E8999,true);v.setGravity(Gravity.CENTER);v.setPadding(dp(8),0,dp(8),0);return v;}private TextView tv(String s,int z,int c,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);if(b)v.setTypeface(Typeface.DEFAULT_BOLD);v.setPadding(dp(5),dp(4),dp(5),dp(4));return v;}private Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(11);b.setAllCaps(false);b.setBackground(round(0xFF14131D,18));return b;}private GradientDrawable round(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
 @Override protected void onDestroy(){if(audio!=null)audio.stop();if(camera!=null)camera.close();if(stt!=null)stt.close();if(neural!=null)neural.close();super.onDestroy();}
}
