package com.imagine.martinhost;

import android.Manifest;
import android.app.Activity;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.os.Bundle;
import android.speech.RecognitionListener;
import android.speech.RecognizerIntent;
import android.speech.SpeechRecognizer;
import android.speech.tts.TextToSpeech;
import android.view.Gravity;
import android.widget.*;
import java.util.*;

public final class MainActivity extends Activity implements RecognitionListener, TextToSpeech.OnInitListener {
    private static final int REQ=7; private SpeechRecognizer sr; private TextToSpeech tts; private GrokClient grok;
    private TextView state,lastHeard,lastReply; private Button main,pause,stop,next; private boolean active,paused,speaking;
    @Override public void onCreate(Bundle b){ super.onCreate(b); buildUi(); grok=new GrokClient(this); tts=new TextToSpeech(this,this); requestPerms(); }
    private void requestPerms(){ ArrayList<String> p=new ArrayList<>(); if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED)p.add(Manifest.permission.RECORD_AUDIO); if(android.os.Build.VERSION.SDK_INT>=31&&checkSelfPermission(Manifest.permission.BLUETOOTH_CONNECT)!=PackageManager.PERMISSION_GRANTED)p.add(Manifest.permission.BLUETOOTH_CONNECT); if(!p.isEmpty())requestPermissions(p.toArray(new String[0]),REQ); }
    private void startListening(){ if(paused||speaking||!active)return; if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPerms();return;} if(sr!=null)try{sr.destroy();}catch(Exception ignored){} sr=SpeechRecognizer.isOnDeviceRecognitionAvailable(this)?SpeechRecognizer.createOnDeviceSpeechRecognizer(this):SpeechRecognizer.createSpeechRecognizer(this); sr.setRecognitionListener(this); Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH); i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM); i.putExtra(RecognizerIntent.EXTRA_LANGUAGE,"ru-RU"); i.putExtra(RecognizerIntent.EXTRA_PARTIAL_RESULTS,true); i.putExtra(RecognizerIntent.EXTRA_PREFER_OFFLINE,true); sr.startListening(i); state.setText("🟢 Слушаю: скажите «Мартин, …»"); }
    private void ask(String q){ speaking=true; if(sr!=null)try{sr.cancel();}catch(Exception ignored){} state.setText("🟡 Мартин думает…"); grok.reply(q,new GrokClient.Callback(){ public void onResult(String text){runOnUiThread(()->{lastReply.setText(text);state.setText("🔊 Мартин говорит…");tts.speak(text,TextToSpeech.QUEUE_FLUSH,null,"martin");});} public void onError(String e){runOnUiThread(()->{speaking=false;state.setText("Ошибка AI");lastReply.setText(e);startListening();});}}); }
    private void hardStop(){ active=false;paused=false;speaking=false;if(sr!=null)try{sr.cancel();}catch(Exception ignored){}if(tts!=null)tts.stop();state.setText("⛔ Остановлено");main.setText("🎙 НАЧАТЬ СЛУШАТЬ"); }
    @Override public void onInit(int s){ if(s==TextToSpeech.SUCCESS){tts.setLanguage(new Locale("ru","RU"));tts.setSpeechRate(1.05f);tts.setOnUtteranceProgressListener(new android.speech.tts.UtteranceProgressListener(){public void onStart(String id){} public void onDone(String id){runOnUiThread(()->{speaking=false;if(active&&!paused)startListening();});} public void onError(String id){runOnUiThread(()->{speaking=false;if(active&&!paused)startListening();});}});}}
    @Override public void onResults(Bundle b){ ArrayList<String> r=b.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION); String t=r==null||r.isEmpty()?"":r.get(0); lastHeard.setText(t); String low=t.toLowerCase(Locale.ROOT); if(low.contains("мартин стоп")||low.equals("стоп")){hardStop();return;} int x=low.indexOf("мартин"); if(x>=0){String q=t.substring(Math.min(t.length(),x+6)).replaceFirst("^[,.:;!?\\s-]+","");if(q.isBlank())q="Поздоровайся и спроси, чем помочь компании.";ask(q);} else if(active&&!paused) startListening(); }
    @Override public void onPartialResults(Bundle b){} @Override public void onReadyForSpeech(Bundle b){} @Override public void onBeginningOfSpeech(){state.setText("🎤 Слышу речь…");} @Override public void onRmsChanged(float v){} @Override public void onBufferReceived(byte[] b){} @Override public void onEndOfSpeech(){state.setText("🟡 Разбираю фразу…");} @Override public void onEvent(int t,Bundle b){} @Override public void onError(int e){ if(active&&!paused&&!speaking)new android.os.Handler(getMainLooper()).postDelayed(this::startListening,350); }
    private TextView tv(String s,int sp,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(c);v.setPadding(8,8,8,8);return v;} private Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;}
    private void buildUi(){ getWindow().setStatusBarColor(0xFF0F1014); LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(24,28,24,28);root.setBackgroundColor(0xFF0F1014); TextView h=tv("КАТЯ • 35",38,Color.WHITE);h.setGravity(Gravity.CENTER);root.addView(h);TextView sub=tv("Мартин — AI ведущий",17,0xFFB9BECA);sub.setGravity(Gravity.CENTER);root.addView(sub);state=tv("Готов",22,0xFFFFD166);state.setGravity(Gravity.CENTER);root.addView(state); main=btn("🎙 НАЧАТЬ СЛУШАТЬ");root.addView(main); LinearLayout row=new LinearLayout(this);pause=btn("☕ ПАУЗА");stop=btn("🛑 СТОП");row.addView(pause,new LinearLayout.LayoutParams(0,-2,1));row.addView(stop,new LinearLayout.LayoutParams(0,-2,1));root.addView(row);next=btn("✨ СЛЕДУЮЩАЯ ИГРА");root.addView(next);root.addView(tv("УСЛЫШАЛ",12,0xFF8F96A3));lastHeard=tv("Скажите: «Мартин, давай игру»",18,Color.WHITE);root.addView(lastHeard);root.addView(tv("МАРТИН",12,0xFFFFD166));lastReply=tv("Здесь появится последняя реплика AI",20,Color.WHITE);root.addView(lastReply);Button settings=btn("⚙ НАСТРОЙКИ / ГОСТИ / API");root.addView(settings);setContentView(root); main.setOnClickListener(v->{active=!active;if(active){paused=false;main.setText("🟢 СЛУШАЮ");startListening();}else hardStop();}); pause.setOnClickListener(v->{paused=!paused;if(paused){if(sr!=null)sr.cancel();if(tts!=null)tts.stop();state.setText("⏸ Пауза");}else{state.setText("Возобновляю…");startListening();}});stop.setOnClickListener(v->hardStop());next.setOnClickListener(v->ask("Предложи следующую короткую веселую активность на 5-10 минут. Выбирай между викториной, Что? Где? Когда?, угадай мелодию, цитатами, логикой, импровизацией, тостом или другой игрой. Учитывай подготовленные сведения о гостях и не нарушай их границы."));settings.setOnClickListener(v->startActivity(new Intent(this,SettingsActivity.class))); }
    @Override protected void onDestroy(){if(sr!=null)sr.destroy();if(tts!=null)tts.shutdown();super.onDestroy();}
}
