package com.imagine.martinhost;

import android.app.Activity;import android.content.Intent;import android.graphics.Color;import android.graphics.Typeface;import android.graphics.drawable.GradientDrawable;import android.net.Uri;import android.os.Bundle;import android.view.Gravity;import android.widget.*;import java.net.URLEncoder;import java.nio.charset.StandardCharsets;
/** Deadline-safe DJ screen: curated blocks open as Yandex Music searches; playback stays in licensed music app. */
public final class MusicActivity extends Activity{
 @Override public void onCreate(Bundle b){super.onCreate(b);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(18),dp(16),dp(18),dp(16));r.setBackgroundColor(0xFF060711);TextView h=t("♫  МУЗЫКА ВЕЧЕРИНКИ",24,Color.WHITE,true);h.setGravity(Gravity.CENTER);r.addView(h,new LinearLayout.LayoutParams(-1,dp(58)));TextView s=t("Готовые музыкальные блоки. Нажатие открывает поиск в Яндекс Музыке — само приложение Martin не хранит музыку и не прерывает её своим интерфейсом.",12,0xFFA8A2B4,false);s.setGravity(Gravity.CENTER);r.addView(s);
  add(r,"🔥 Разогрев • 90-е / 00-е","Руки Вверх Дискотека Авария Иванушки Hi-Fi гости из 90-х");add(r,"💃 Танцы • русские хиты","русские танцевальные хиты 2000 2010 вечеринка");add(r,"✨ Хиты 2026","популярные хиты 2026 русские зарубежные");add(r,"🌙 Медляки","медленные хиты 90 2000 романтика");add(r,"🏊 Лето / бассейн","летние хиты dance pool party");add(r,"🎂 День рождения","день рождения вечеринка хиты");
  Button back=b("‹  НАЗАД");back.setOnClickListener(v->finish());r.addView(back,new LinearLayout.LayoutParams(-1,dp(54)));setContentView(r);}
 private void add(LinearLayout r,String label,String q){Button b=b(label);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(58));p.setMargins(0,dp(8),0,0);r.addView(b,p);b.setOnClickListener(v->open(q));}
 private void open(String q){try{String e=URLEncoder.encode(q,StandardCharsets.UTF_8.toString());startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://music.yandex.ru/search?text="+e)));}catch(Exception x){Toast.makeText(this,"Не удалось открыть музыкальное приложение",Toast.LENGTH_SHORT).show();}}
 private Button b(String x){Button b=new Button(this);b.setText(x);b.setTextColor(Color.WHITE);b.setTextSize(14);b.setAllCaps(false);b.setTypeface(Typeface.DEFAULT_BOLD);b.setBackground(round(0xFF171421,18));return b;}private TextView t(String x,int z,int c,boolean bold){TextView v=new TextView(this);v.setText(x);v.setTextSize(z);v.setTextColor(c);if(bold)v.setTypeface(Typeface.DEFAULT_BOLD);v.setPadding(dp(6),dp(6),dp(6),dp(6));return v;}private GradientDrawable round(int c,int rr){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(rr));return g;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
