package com.imagine.martinhost;
import android.app.*;import android.content.*;import android.net.Uri;import android.os.Bundle;import android.provider.OpenableColumns;import android.widget.*;
public final class MusicActivity extends Activity {
 private PartyMusic music;private TextView status;private LinearLayout list;
 public void onCreate(Bundle b){super.onCreate(b);music=PartyMusic.get(this);LinearLayout root=PartyScreen.root(this,"Музыка / плейлист");
 status=PartyScreen.text(this,root,music.status(),17);
 PartyScreen.text(this,root,"Добавьте купленные или свои аудиофайлы. Треки остаются на телефоне. Для музыкальных конкурсов укажите исполнителя, название и год. Яндекс Музыка открывается отдельно: приложение не управляет её защищённым каталогом.",14);
 PartyScreen.button(this,root,"＋ Добавить аудиофайлы",()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("audio/*");i.addCategory(Intent.CATEGORY_OPENABLE);i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,31);});
 PartyScreen.button(this,root,"▶ / Ⅱ Воспроизведение",()->music.toggle());PartyScreen.button(this,root,"Следующий трек →",()->music.next());PartyScreen.button(this,root,"← Предыдущий трек",()->music.previous());PartyScreen.button(this,root,"■ Стоп",()->music.stop());
 Button auto=PartyScreen.button(this,root,autoLabel(),()->{});auto.setOnClickListener(v->{boolean on=!getSharedPreferences("martin",0).getBoolean("auto_music",true);getSharedPreferences("martin",0).edit().putBoolean("auto_music",on).apply();auto.setText(autoLabel());if(on)music.ensureBackground();else music.stopBackground();});
 PartyScreen.button(this,root,"Открыть Яндекс Музыку",()->open("https://music.yandex.ru/"));
 PartyScreen.button(this,root,"Ностальгия: 90-е и 2000-е",()->open("https://music.yandex.ru/search?text="+Uri.encode("Хиты 90-х и 2000-х")));
 PartyScreen.button(this,root,"Актуальный чарт",()->open("https://music.yandex.ru/chart"));
 PartyScreen.text(this,root,"Программа вечера: встреча — спокойный фон; застолье — знакомые песни; конкурсы — короткие отрывки; танцы — 90-е/00-е; финал — медляки. Начальная подборка ниже — ссылки на поиск, не скачанные треки.",14);
 for(String t:new String[]{"Sade — Smooth Operator","Руки Вверх! — Крошка моя","Иванушки International — Тополиный пух","Дискотека Авария — Если хочешь остаться","Демо — Солнышко","Вирус! — Ты меня не ищи","t.A.T.u. — Нас не догонят","Звери — Районы-кварталы","МакSим — Знаешь ли ты","Мумий Тролль — Владивосток 2000"})PartyScreen.button(this,root,"↗ "+t,()->open("https://music.yandex.ru/search?text="+Uri.encode(t)));
 list=new LinearLayout(this);list.setOrientation(1);root.addView(list);render();music.setListener(s->runOnUiThread(()->status.setText(s)));
 PartyScreen.button(this,root,"Очистить список",()->new AlertDialog.Builder(this).setMessage("Убрать треки из плейлиста? Сами файлы не удалятся.").setPositiveButton("Очистить",(d,w)->{music.clear();render();}).setNegativeButton("Отмена",null).show());}
 private void open(String u){try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(u)));}catch(Exception e){status.setText("Не найдено приложение для открытия ссылки");}}
 private void render(){list.removeAllViews();int i=0;for(PartyMusic.Track t:music.tracks()){final int n=i++;PartyScreen.button(this,list,"▶ "+t.artist+" — "+t.title+(t.year>0?" • "+t.year:""),()->music.play(n));PartyScreen.button(this,list,"Данные трека",()->edit(n,t));}}
 private void edit(int i,PartyMusic.Track t){LinearLayout l=new LinearLayout(this);l.setOrientation(1);EditText title=new EditText(this);title.setHint("Название");title.setText(t.title);l.addView(title);EditText artist=new EditText(this);artist.setHint("Исполнитель");artist.setText(t.artist);l.addView(artist);EditText year=new EditText(this);year.setHint("Год, например 1998");year.setInputType(2);year.setText(t.year>0?""+t.year:"");l.addView(year);new AlertDialog.Builder(this).setTitle("Данные для угадывания").setView(l).setPositiveButton("Сохранить",(d,w)->{int y=0;try{y=Integer.parseInt(year.getText().toString());}catch(Exception ignored){}music.edit(i,title.getText().toString(),artist.getText().toString(),y);render();}).setNegativeButton("Отмена",null).show();}
 @Override protected void onActivityResult(int r,int c,Intent data){super.onActivityResult(r,c,data);if(r!=31||c!=RESULT_OK||data==null)return;if(data.getClipData()!=null){for(int i=0;i<data.getClipData().getItemCount();i++)add(data.getClipData().getItemAt(i).getUri(),data.getFlags());}else if(data.getData()!=null)add(data.getData(),data.getFlags());render();}
 private void add(Uri u,int flags){try{getContentResolver().takePersistableUriPermission(u,flags&Intent.FLAG_GRANT_READ_URI_PERMISSION);String name="Трек";try(android.database.Cursor c=getContentResolver().query(u,null,null,null,null)){if(c!=null&&c.moveToFirst()){int x=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(x>=0)name=c.getString(x);}}music.add(u.toString(),name);}catch(Exception e){status.setText("Не удалось добавить файл");}}
 @Override protected void onDestroy(){music.setListener(null);super.onDestroy();}
 private String autoLabel(){return getSharedPreferences("martin",0).getBoolean("auto_music",true)?"♫ ФОНОВАЯ МУЗЫКА: АВТО":"♫ ФОНОВАЯ МУЗЫКА: ВЫКЛ";}
}
