package com.imagine.martinhost;
import android.app.*;import android.content.*;import android.net.Uri;import android.os.Bundle;import android.provider.OpenableColumns;import android.widget.*;
public final class MusicActivity extends Activity {
 private PartyMusic music;private TextView status,yandexStatus;private LinearLayout list;private static final int REQ_YANDEX=44;
 public void onCreate(Bundle b){super.onCreate(b);music=PartyMusic.get(this);LinearLayout root=PartyScreen.root(this,"Музыка / плейлист");
 status=PartyScreen.text(this,root,music.status(),17);
 yandexStatus=PartyScreen.text(this,root,yandexLabel(),15);
 PartyScreen.text(this,root,"Для голосовых заявок и «Угадай мелодию» используется прямое воспроизведение через ваш аккаунт Яндекс Музыки. Войти нужно один раз; пароль остаётся на странице Яндекса.",14);
 PartyScreen.button(this,root,"🔐 Подключить Яндекс для автоигр",()->startActivityForResult(new Intent(this,YandexAuthActivity.class),REQ_YANDEX));
 PartyScreen.button(this,root,"▶ Тест Яндекс Музыки",()->testYandex());
 PartyScreen.button(this,root,"＋ Добавить аудиофайлы",()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("audio/*");i.addCategory(Intent.CATEGORY_OPENABLE);i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,31);});
 PartyScreen.button(this,root,"▶ / Ⅱ Локальное воспроизведение",()->music.toggle());PartyScreen.button(this,root,"Следующий локальный трек →",()->music.next());PartyScreen.button(this,root,"← Предыдущий локальный трек",()->music.previous());PartyScreen.button(this,root,"■ Стоп всей музыки",()->music.stop());
 Button auto=PartyScreen.button(this,root,autoLabel(),()->{});auto.setOnClickListener(v->{boolean on=!getSharedPreferences("martin",0).getBoolean("auto_music",true);getSharedPreferences("martin",0).edit().putBoolean("auto_music",on).apply();auto.setText(autoLabel());if(on)music.ensureBackground();else music.stopBackground();});
 PartyScreen.button(this,root,"Открыть Яндекс Музыку вручную",()->startActivity(new Intent(this,YandexMusicWebActivity.class)));
 PartyScreen.button(this,root,"Ностальгия: 90-е и 2000-е",()->open("https://music.yandex.ru/search?text="+Uri.encode("Хиты 90-х и 2000-х")));
 PartyScreen.button(this,root,"Актуальный чарт",()->open("https://music.yandex.ru/chart"));
 PartyScreen.text(this,root,"Если кнопка «Тест Яндекс Музыки» играет трек, голосовые заявки и музыкальная викторина используют тот же прямой плеер. Старый скрытый WebView больше не нужен для автоматического Play.",14);
 for(String t:new String[]{"Sade — Smooth Operator","Руки Вверх! — Крошка моя","Иванушки International — Тополиный пух","Дискотека Авария — Если хочешь остаться","Демо — Солнышко","Вирус! — Ты меня не ищи","t.A.T.u. — Нас не догонят","Звери — Районы-кварталы","МакSим — Знаешь ли ты","Мумий Тролль — Владивосток 2000"})PartyScreen.button(this,root,"↗ "+t,()->open("https://music.yandex.ru/search?text="+Uri.encode(t)));
 list=new LinearLayout(this);list.setOrientation(1);root.addView(list);render();music.setListener(s->runOnUiThread(()->status.setText(s)));
 PartyScreen.button(this,root,"Очистить локальный список",()->new AlertDialog.Builder(this).setMessage("Убрать локальные треки из плейлиста? Сами файлы не удалятся.").setPositiveButton("Очистить",(d,w)->{music.clear();render();}).setNegativeButton("Отмена",null).show());}
 private String yandexLabel(){return YandexMusicClient.get(this).hasToken()?"● Яндекс подключён для автоигр":"○ Яндекс не подключён для автоигр";}
 private void testYandex(){YandexMusicClient c=YandexMusicClient.get(this);if(!c.hasToken()){yandexStatus.setText("Сначала нажмите «Подключить Яндекс для автоигр»");startActivityForResult(new Intent(this,YandexAuthActivity.class),REQ_YANDEX);return;}status.setText("Проверяю прямое воспроизведение…");c.setVolume(1f);c.play("Руки Вверх Крошка моя",new YandexMusicClient.Callback(){public void onStarted(YandexMusicClient.TrackInfo t){runOnUiThread(()->{status.setText("Играет: "+t.label());yandexStatus.setText("● Яндекс подключён и воспроизводит");});}public void onFinished(YandexMusicClient.TrackInfo t){}public void onError(String e){runOnUiThread(()->{status.setText("Ошибка Яндекс Музыки: "+e);yandexStatus.setText(yandexLabel());});}});}
 private void open(String u){try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(u)));}catch(Exception e){status.setText("Не найдено приложение для открытия ссылки");}}
 private void render(){list.removeAllViews();int i=0;for(PartyMusic.Track t:music.tracks()){final int n=i++;PartyScreen.button(this,list,"▶ "+t.artist+" — "+t.title+(t.year>0?" • "+t.year:""),()->music.play(n));PartyScreen.button(this,list,"Данные трека",()->edit(n,t));}}
 private void edit(int i,PartyMusic.Track t){LinearLayout l=new LinearLayout(this);l.setOrientation(1);EditText title=new EditText(this);title.setHint("Название");title.setText(t.title);l.addView(title);EditText artist=new EditText(this);artist.setHint("Исполнитель");artist.setText(t.artist);l.addView(artist);EditText year=new EditText(this);year.setHint("Год, например 1998");year.setInputType(2);year.setText(t.year>0?""+t.year:"");l.addView(year);new AlertDialog.Builder(this).setTitle("Данные для угадывания").setView(l).setPositiveButton("Сохранить",(d,w)->{int y=0;try{y=Integer.parseInt(year.getText().toString());}catch(Exception ignored){}music.edit(i,title.getText().toString(),artist.getText().toString(),y);render();}).setNegativeButton("Отмена",null).show();}
 @Override protected void onActivityResult(int r,int c,Intent data){super.onActivityResult(r,c,data);if(r==REQ_YANDEX){yandexStatus.setText(yandexLabel());if(c==RESULT_OK)status.setText("Яндекс Музыка подключена. Можно проверить кнопкой теста.");return;}if(r!=31||c!=RESULT_OK||data==null)return;if(data.getClipData()!=null){for(int i=0;i<data.getClipData().getItemCount();i++)add(data.getClipData().getItemAt(i).getUri(),data.getFlags());}else if(data.getData()!=null)add(data.getData(),data.getFlags());render();}
 private void add(Uri u,int flags){try{getContentResolver().takePersistableUriPermission(u,flags&Intent.FLAG_GRANT_READ_URI_PERMISSION);String name="Трек";try(android.database.Cursor c=getContentResolver().query(u,null,null,null,null)){if(c!=null&&c.moveToFirst()){int x=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(x>=0)name=c.getString(x);}}music.add(u.toString(),name);}catch(Exception e){status.setText("Не удалось добавить файл");}}
 @Override protected void onResume(){super.onResume();if(yandexStatus!=null)yandexStatus.setText(yandexLabel());}
 @Override protected void onDestroy(){music.setListener(null);super.onDestroy();}
 private String autoLabel(){return getSharedPreferences("martin",0).getBoolean("auto_music",true)?"♫ ФОНОВАЯ МУЗЫКА: АВТО":"♫ ФОНОВАЯ МУЗЫКА: ВЫКЛ";}
}
