package com.imagine.martinhost;
import android.app.Activity;import android.graphics.Color;import android.net.Uri;import android.os.*;import android.view.*;import android.webkit.*;
/** Hidden web player sharing the cookies created by the visible login screen. */
final class YandexMusicPlayback {
 private static WebView web;private static Activity owner;private static final Handler ui=new Handler(Looper.getMainLooper());private static String pending="";
 static void attach(Activity a,ViewGroup root){release();owner=a;web=new WebView(a);web.setBackgroundColor(Color.TRANSPARENT);web.setAlpha(.01f);root.addView(web,new ViewGroup.LayoutParams(2,2));WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setDatabaseEnabled(true);s.setMediaPlaybackRequiresUserGesture(false);s.setAllowFileAccess(false);s.setAllowContentAccess(false);s.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);s.setSafeBrowsingEnabled(true);CookieManager.getInstance().setAcceptCookie(true);CookieManager.getInstance().setAcceptThirdPartyCookies(web,true);web.setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){return !allowed(r.getUrl());}@Override public void onPageFinished(WebView v,String url){if(!pending.isBlank())schedule();}});}
 static boolean play(String q){if(web==null||q==null||q.isBlank())return false;pending=q;DiagnosticRecorder.get(owner).event("music_web","search_start;query="+q);web.loadUrl("https://music.yandex.ru/search?text="+Uri.encode(q));return true;}
 private static void schedule(){for(long d:new long[]{700,1800,3500,6000})ui.postDelayed(YandexMusicPlayback::tryClick,d);}
 private static void tryClick(){if(web==null||pending.isBlank())return;String js="(()=>{const vis=e=>e&&e.getClientRects().length>0;const txt=e=>((e.getAttribute('aria-label')||'')+' '+(e.title||'')+' '+(e.textContent||'')).toLowerCase();const links=[...document.querySelectorAll('a[href*=\\\"/track/\\\"],a[href*=\\\"trackId=\\\"]')].filter(vis);if(links.length){const row=links[0].closest('[data-test-id],article,li,div');const b=row&&[...row.querySelectorAll('button,[role=button]')].find(x=>vis(x)&&/(воспроиз|слушать|play)/.test(txt(x)));if(b){b.click();return 'row-play';}if(!location.href.includes('/track/')){links[0].click();return 'open-track';}}const b=[...document.querySelectorAll('button,[role=button]')].find(x=>vis(x)&&/(воспроизвести|слушать|play)/.test(txt(x)));if(b){b.click();return 'page-play';}return 'not-found';})()";web.evaluateJavascript(js,r->{DiagnosticRecorder.get(owner).event("music_web","automation="+r);if(r!=null&&r.contains("play"))pending="";});}
 static void stop(){pending="";if(web!=null)web.evaluateJavascript("document.querySelectorAll('audio,video').forEach(x=>x.pause())",null);}
 static void release(){ui.removeCallbacksAndMessages(null);if(web!=null){web.stopLoading();web.destroy();web=null;}owner=null;pending="";}
 private static boolean allowed(Uri u){String h=u.getHost();return "https".equalsIgnoreCase(u.getScheme())&&h!=null&&(h.equals("yandex.ru")||h.endsWith(".yandex.ru")||h.equals("yandex.com")||h.endsWith(".yandex.com")||h.equals("yandex.net")||h.endsWith(".yandex.net")||h.equals("ya.ru")||h.endsWith(".ya.ru"));}
 private YandexMusicPlayback(){}
}
