package com.imagine.martinhost;
import org.junit.Test;import static org.junit.Assert.*;import java.util.*;

public class PartyDirectorTest {
 @Test public void waitsForReadyAndFinalAnswerThenScoresOnce(){List<String> scores=new ArrayList<>();PartyDirector d=new PartyDirector(scores::add);d.startChgk();assertEquals(PartyDirector.Mode.RULES,d.mode());d.onUserText("не сейчас");assertEquals(PartyDirector.Mode.RULES,d.mode());d.onUserText("начинаем");assertEquals(PartyDirector.Mode.WAIT_ANSWER,d.mode());d.onUserText("может яма");assertEquals(PartyDirector.Mode.WAIT_ANSWER,d.mode());d.onUserText("ответ яма");assertEquals(PartyDirector.Mode.WAIT_NAME,d.mode());d.onUserText("Катя");assertEquals(Arrays.asList("Катя"),scores);d.onUserText("Катя");assertEquals(1,scores.size());}
 @Test public void cancelReturnsToChatAndCannotAward(){List<String> s=new ArrayList<>();PartyDirector d=new PartyDirector(s::add);d.startGame("expert");d.next();d.cancel();d.award();assertTrue(s.isEmpty());assertEquals(PartyDirector.Mode.FREE,d.mode());assertTrue(d.onUserText("привет").askAi);}
 @Test public void revealDoesNotAwardAndRoundsEnd(){List<String> s=new ArrayList<>();PartyDirector d=new PartyDirector(s::add);d.startChgk();for(int i=0;i<6;i++){d.next();d.reveal();}d.next();assertEquals(PartyDirector.Mode.FREE,d.mode());assertTrue(s.isEmpty());}
 @Test public void knownCameraGuestGetsPointWithoutSecondQuestion(){List<String> s=new ArrayList<>();PartyDirector d=new PartyDirector(s::add);d.startChgk();d.next();d.setSuggestedGuest("Андрей");PartyDirector.Action a=d.onUserText("ответ яма");assertEquals(PartyDirector.Mode.RESULT,d.mode());assertEquals(Collections.singletonList("Андрей"),s);assertTrue(a.speech.contains("Андрей"));}
 @Test public void unknownGuestIsAsked(){List<String> s=new ArrayList<>();PartyDirector d=new PartyDirector(s::add);d.startChgk();d.next();PartyDirector.Action a=d.onUserText("ответ яма");assertEquals(PartyDirector.Mode.WAIT_NAME,d.mode());assertTrue(a.speech.contains("не уверен"));}
 @Test public void scheduledGameRequiresConsent(){PartyDirector d=new PartyDirector(name->{});d.offerGame("true_false");assertEquals(PartyDirector.Mode.OFFER,d.mode());d.onUserText("не сейчас");assertEquals(PartyDirector.Mode.FREE,d.mode());d.offerGame("true_false");d.onUserText("давай");assertEquals(PartyDirector.Mode.RULES,d.mode());}
 @Test public void melodyKnownGuestAutoAdvancesWithoutSayingNext(){List<String> s=new ArrayList<>();PartyDirector d=new PartyDirector(s::add);d.startGame("melody");d.onUserText("начинаем");d.setSuggestedGuest("Катя");PartyDirector.Action a=d.award();assertEquals(Collections.singletonList("Катя"),s);assertEquals(PartyDirector.Mode.WAIT_ANSWER,d.mode());assertTrue(d.summary().contains("раунд 2"));assertTrue(a.speech.contains("Раунд 2"));}
 @Test public void melodyUnknownGuestNameAlsoAutoAdvances(){List<String> s=new ArrayList<>();PartyDirector d=new PartyDirector(s::add);d.startGame("melody");d.onUserText("начинаем");d.award();assertEquals(PartyDirector.Mode.WAIT_NAME,d.mode());PartyDirector.Action a=d.onUserText("Катя");assertEquals(Collections.singletonList("Катя"),s);assertEquals(PartyDirector.Mode.WAIT_ANSWER,d.mode());assertTrue(a.speech.contains("Раунд 2"));}
 @Test public void melodySixthRoundAnnouncesCheckpoint(){List<String> s=new ArrayList<>();PartyDirector d=new PartyDirector(s::add);d.startGame("melody");d.onUserText("начинаем");PartyDirector.Action a=null;for(int i=0;i<6;i++){d.setSuggestedGuest("Катя");a=d.award();}assertNotNull(a);assertTrue(a.speech.contains("Промежуточный"));assertTrue(d.summary().contains("раунд 7"));}
 @Test public void melodyFinalRoundIsTripleAndEndsAutomatically(){List<String> s=new ArrayList<>();PartyDirector d=new PartyDirector(s::add);d.startGame("melody");d.onUserText("начинаем");for(int i=0;i<17;i++)d.reveal();assertTrue(d.summary().contains("раунд 18"));d.setSuggestedGuest("Катя");PartyDirector.Action a=d.award();assertEquals(Arrays.asList("Катя","Катя","Катя"),s);assertEquals(PartyDirector.Mode.FREE,d.mode());assertTrue(a.speech.contains("Финал"));}
 @Test public void sttTypoStillStartsMelodyGame(){PartyDirector d=new PartyDirector(name->{});PartyDirector.Action a=d.onUserText("Давай поиграем в отгода мелодию");assertEquals(PartyDirector.Mode.RULES,d.mode());assertTrue(a.speech.contains("Угадай мелодию"));}
}
